import {
  Inter,
  Lato,
  Lobster,
  Montserrat,
  Nunito,
  Micro_5,
} from "next/font/google";
import "./globals.css";
const inter = Nunito({
  family: ["Nunito", "sans-serif"],
  weight: ["400"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});
import Nav from "./Components/Dashboard/Nav/page";
import Session from './Session/page'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <Session>
    <body className={` bg-slate-800  text-slate-400 ${inter.className}`}>
        <div className=" fl,ex ">
          {/* <Nav /> */}
          {children}
        </div>
      </body>
    </Session>
    </html>
  );
}
